### ISSUE TITLE
TypeScript: Cannot find module 'diary' or its corresponding type declarations

### ISSUE THREAD

**Issue by abeforgit** [maraisr/diary#11]
While #9 is marked as solved, I still have that issue. However, the workaround mentioned [there](https://github.com/maraisr/diary/issues/9#issuecomment-850714044) to add the module definition like so:
```ts
// global.d.ts

declare module 'diary' {
    export * from 'diary/types/index';
}
```
works well. So this is not really blocking, but it being a fully typescript library it's a bit weird to have to add these module definitions.

## Environment

I am running a bit of a weird setup so this might be the cause

node: v14.16.0
npm: 6.4.11
typescript: 3.9.1-rc

It is also an [emberJS](https://emberjs.com/) project, which has its own rather opaque build system

**Comment by maraisr** [comment]
Hi @abeforgit  thanks for the issue! Yeah that isnt the greatest DX for sure. But in [0.1.4](https://github.com/maraisr/diary/releases/tag/0.1.4) we did release a fix that made it so the typings all work as it should. 

But in saying that i see you're using TypeScript 3 — maybe all i need to do is check when `typeVersions` as introduced and set that is its version, currently its [`> 4`](https://github.com/maraisr/diary/blob/main/package.json#L39)

**Comment by abeforgit** [comment]
ah yes thatll be it
I'll see if I can't make a pr to support lower ts versions, upgrading is a bit of a battle on our end

**Comment by abeforgit** [comment]
I'd suggest adding to the README that currently only ts >4 is supported, I'd consider this issue as resolved then

**Comment by maraisr** [comment]
I don't think any of the TypeScript itself is a hard and fast v4+, do you mind helping me test this? Can you open up `node_modules/diary/package.json` and change the typeVersions to >3 ald let me know if that works for you.

If that works we can surely raise a PR.

**Comment by abeforgit** [comment]
Taking the version down works indeed, but it's not quite that simple. Taking the version down implies we would support that version of typescript, which is actually quite annoying to verify if we want to keep developing using the latest typescript compiler.
Reference here: https://github.com/microsoft/TypeScript/issues/31907
There is this package: https://github.com/sandersn/downlevel-dts which attempts to automatically create "polyfills" for older typescript versions, but it's not perfect and they explicitly say you'd need to verify it manually with the specific tsc version.

On the other hand, since this is really only an issue about types, not about functionality, it wouldn't be too bad to just kind of assume things will work and handle issues as they appear

I had no idea packaging ts projects was this much of a pain :sweat_smile: this is my first experience with it

**Comment by abeforgit** [comment]
In any case if you do end up going for it I'd suggest targeting 3.4 or higher, to keep the option for using downlevel-dts open

**Comment by abeforgit** [comment]
Fyi I did end up just updating our typescript version to latest, it was not painful at all :) for me you can close this issue, maybe still add a hint in the readme that if people need support for lower versions they can raise an issue?
