### ISSUE TITLE
[Bug] Handle cases where localStorage is not available.

### ISSUE THREAD

**Issue by abeforgit** [maraisr/diary#15]
Turns out localStorage is not always accessible in the browser. In my particular usecase, my app was used in an iframe, and chrome with restrictive 3rd party cookie settings throws an error when trying to access localstorage. This would be fine if the error would be thrown when using diary's functions, cause then I would simply catch that error in my app. However, because diary tries to access localStorage directly at the top level of the module, this error gets thrown on import of any diary function.

I could probably try/catch the whole file I'm using diary in, but that's not very nice. Ideally diary would delay access to localStorage until it needs it in the reporter, so there are options for consuming code to provide alternatives when localStorage is not available.

**Comment by maraisr** [comment]
Ahhh yeah good catch. Never actually found a time where that would be inactive in the wild, but there it is. iframes! nice. I originally wanted it in the module scope, so the cost is paid once. As variable lookup is far cheaper than localStorage.

What would you say is an alternative? Ideally diary shouldn't break here, but have a fallback, or maybe amend the pipes a little and ya do as you say. Handle it in the reporter.

cc @lukeed  care to chime in here?

**Comment by abeforgit** [comment]
apologies for the long delay of the response, I've been swamped with deadlines and other concerns so the logging experiment has fallen down the backlog. 
I haven't completely thought this through, but I think just testing for it on first request rather than on module load and then caching it might already be enough. 

Another approach that I've seen in other libraries is requiring the user to call some sort of `enable` or `setup` function before using the library, which also seems sensible (this also gives users more control, however does introduce an extra setup step)

**Comment by maraisr** [comment]
Hi @abeforgit sorry for this delay, but thank you for being so patient 🥲

We no longer `enable` by default in browser runtimes. This should mean you can handle the localStorage exception in your side.
