### ISSUE TITLE
`LogFnAsError` type missing from `src/index.d.ts`

### ISSUE THREAD

**Issue by maxmilton** [maraisr/diary#20]
### Describe the bug

After <https://github.com/maraisr/diary/commit/78334b38ac7a41e33169562c17829933fd2479b9> the types in <https://github.com/maraisr/diary/blob/a723e0b203321faa6a95195c9991c2cf74c67427/src/index.d.ts> are broken. Specifically, a type definition for `LogFnAsError` is now missing.

This means that any use of `customLogger.error(...)` and `customLogger.fatal(...)` in a typescript project doesn't work as expected.

### To reproduce

```ts
import { diary } from 'diary';

const customLogger = diary('');

customLogger.error(new Error('test'));
```

Typescript can't see any type definition for `LogFnAsError` and treats it as `any`. When using `@typescript-eslint/eslint-plugin` in a project, a lint error for the rule `@typescript-eslint/no-unsafe-call` is emitted for `customLogger.error`.

### Expected behavior

`customLogger.error(...)` and `customLogger.fatal(...)` are typed correctly.

**Comment by maxmilton** [comment]
Created a fix PR in <https://github.com/maraisr/diary/pull/21>.

I also suggest adding linting to this project which would catch bugs like this.

**Comment by maraisr** [comment]
Yeah ouch... bad moment! Sorry about this. Ill get this out asap. 

In terms of testing, yeah think I better — this hasn't been the first time. Thanks for jumping on it.

**Comment by maraisr** [comment]
I think with this commit (https://github.com/maraisr/diary/commit/24f058818cecd2b4c592cc4cbce67551e958b493) we should now have tests for our types as well.

Thanks for the highlight.

also `v0.4.3` has the fix applied.
