### ISSUE TITLE
Trying to access process.env

### ISSUE THREAD

**Issue by BraunreutherA** [maraisr/diary#22]
### Describe the bug

Hey there, 

using diary in Frontend environments bundled by webpack, vite or other without defining the `process.env` variable the library crashes.

I've identified that it tries to access it in the [index.ts](https://github.com/maraisr/diary/blob/main/src/index.ts) file when it thinks it's in a `node` porcess. Actually it should correctly identify that it's getting used in a browser.

Best 

Alex

### To reproduce

Use diary in a browser project which doesn't use process.env.

### Expected behavior

It should not crash - by detecting it's running in a browser instead of a node.js process

**Comment by BraunreutherA** [comment]
I've found out that the `__TARGET__` var is used for your build step and the problem is in the `exports` map of the package.json. 

```
"exports": {
		".": {
			"browser": {
				"types": "./diary/browser/index.d.ts",
				"import": "./diary/browser/index.mjs",
				"require": "./diary/browser/index.js"
			},
			"types": "./diary/node/index.d.ts",
			"import": "./diary/node/index.mjs", // <- the browser selects this one
			"require": "./diary/node/index.js"
		},
		...
	}
```

I'm not sure but it seems that the bundle tools like vite don't pick the correct import here. Do you have any idea why that could be?

**Comment by maraisr** [comment]
Hi @BraunreutherA mega sorry for leaving this for like 6months!!! 😢 

Wondering how you went? Not sure what the defaults are for `vite` but looks like if you set the config `build.target: 'browser'` it sets the correct conditionals. 

👉 https://stackblitz.com/edit/vitejs-vite-kewgxu
