### ISSUE TITLE
[RFC] Always "log" just don't output

### ISSUE THREAD

**Issue by maraisr** [maraisr/diary#7]
## Situation

Currently `diary` before any middleware is processed we check if the currently configured level matches that log event. ie `diary.info` will not _run_ when the level is set to `fatal` for instance.

https://github.com/maraisr/diary/blob/0170945748168a5fa4b9b2927371f5d7d20bb3b5/src/index.ts#L44-L45

Secondly, if this level matches, we then check that it matches an item in the allow list, eg `DEBUG=test:*` when `diary('test')`.

https://github.com/maraisr/diary/blob/0170945748168a5fa4b9b2927371f5d7d20bb3b5/src/index.ts#L47-L50

When in practice only `level` should prohibit logs, and rather `allow_list` should only influence the console output.

## Solution

We move the allow list check till after the middlewares are ran to simply control the console output. 

This approach should also allow for different styles of outputs, and potentially make the `console` out fall into a middlware itself—and aid at resolving #4

**Comment by theKashey** [comment]
It might be interesting to have two levels of middlewares 
- one which always works
- another which is used only when "enabled"
